packages:
  - packages/*
  - apps/*

catalog:
  "@tanstack/react-form": ^1.23.7
  "@types/react": ^19.1.13
  "@types/react-dom": ^19.1.9
  hono: ^4.9.9
  react: ^19.1.1
  react-dom: ^19.1.1
  tailwindcss: ^4.1.13
  tw-animate-css: ^1.4.0
  zod: 4.1.11

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - unrs-resolver
