import z from "zod";

export const TranscriptionSchema = z.object({
  id: z.string(),
  userId: z.string().nullable(),
  moduleUsageId: z.string().nullable(),
  fileName: z.string(),
  filePath: z.string().nullable(),
  fileSize: z.number().nullable(),
  fileType: z.string().nullable(),
  fileUrl: z.string().nullable(),
  transcriptionType: z.string(),
  language: z.string().nullable(),
  quality: z.string().nullable(),
  outputFormat: z.string().nullable(),
  speakerDiarization: z.boolean().nullable(),
  removeFillers: z.boolean().nullable(),
  addPunctuation: z.boolean().nullable(),
  addTimestamps: z.boolean().nullable(),
  generateSummary: z.boolean().nullable(),
  customInstructions: z.string().nullable(),
  publishToContent: z.boolean().nullable(),
  status: z.string().nullable(),
  transcriptText: z.string().nullable(),
  summaryText: z.string().nullable(),
  speakers: z.any().nullable(),
  segments: z.any().nullable(),
  confidenceScore: z.number().nullable(),
  errorMessage: z.string().nullable(),
  retryCount: z.number().nullable(),
  n8nExecutionId: z.string().nullable(),
  n8nWebhookUrl: z.string().nullable(),
  expiresAt: z.string().nullable(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
  completedAt: z.string().nullable(),
});

export type Transcription = z.infer<typeof TranscriptionSchema>;
